# group_vars/jail_posgresql.yml
---

postgresql_root_password: "{{ vault_postgresql_root_password }}"

jail_roles:
  - postgresql

postgresql_version: 18
postgresql_data_dir: "/var/db/postgres/data{{ postgresql_version }}"
