# inventory/hosts.yml
---
all:
  hosts:
    ruru:
      ansible_host: 127.0.0.1
      ansible_connection: local

  children:
    bastille_jails:
      vars:
        ansible_connection: jail
        ansible_become: true
        ansible_python_interpreter: /usr/local/bin/python
        release: "{{ bastille_release }}"
        interface: lo1
      children:
        jail_postgresql:
          hosts:
            postgres-new:
              ansible_jail_name: postgres-new
              staging_ip: 10.2.2.12
              target_ip: 10.2.2.2

        jail_nextcloud:
          hosts:
            nextcloud-new:
              ansible_jail_name: nextcloud-new
              staging_ip: 10.2.2.13
              target_ip: 10.2.2.3
              db_host: 10.2.2.12
              db_name: nextcloud

        jail_kanboard:
          hosts:
            kanboard-new:
              ansible_jail_name: kanboard-new
              staging_ip: 10.2.2.14
              target_ip: 10.2.2.4
              db_host: 10.2.2.12
