all:
  hosts:
    ruru:
      ansible_host: 127.0.0.1
      ansible_connection: local

  children:
    bastille_jails:
      vars:
        ansible_connection: jail
        release: "{{ bastille_release }}"
        interface: lo1
      hosts:
        postgres-new:
          ansible_jail_name: postgres-new
          staging_ip: 10.2.2.12
          target_ip: 10.2.2.2

        nextcloud-new:
          ansible_jail_name: nextcloud-new
          staging_ip: 10.2.2.13
          target_ip: 10.2.2.3
          db_host: 10.2.2.12
          db_name: nextcloud
          db_user: nextcloud
          db_pass: skyhawk1

        kanboard-new:
          ansible_jail_name: kanboard-new
          staging_ip: 10.2.2.14
          target_ip: 10.2.2.4
          db_host: 10.2.2.12
          db_name: kanboard_db
          db_user: kandboard_user
          db_pass: skyhawk1
