# roles/bastille_jail/tasks/main.yml
---

- name: Ensure Bastille release is bootstrapped
  ansible.builtin.command: bastille bootstrap {{ bastille_release }} # noqa: command-instead-of-module
  args:
    creates: "/usr/local/bastille/releases/{{ bastille_release }}"

- name: Create thick jail if it does not exist
  ansible.builtin.command: > # noqa: command-instead-of-module
    bastille create -T {{ item }}
    {{ hostvars[item].release | default(bastille_release) }}
    {{ hostvars[item].staging_ip }}/32
    {{ hostvars[item].interface | default(bastille_interface) }}
  args:
    creates: "/usr/local/bastille/jails/{{ item }}"
  loop: "{{ groups['bastille_jails'] }}"

- name: Create thick jail if it does not exist
  ansible.builtin.command: >
    bastille create -T {{ item }}
    {{ hostvars[item].release | default(bastille_release) }}
    {{ hostvars[item].staging_ip }}/32
    {{ hostvars[item].interface | default(bastille_interface) }}
  args:
    creates: "/usr/local/bastille/jails/{{ item }}"
  loop: "{{ groups['bastille_jails'] }}"

- name: Create package mount point inside jail filesystem on host
  ansible.builtin.file:
    path: "/usr/local/bastille/jails/{{ item }}/root{{ jail_pkg_mount_dir }}"
    state: directory
    mode: '0755'
  loop: "{{ groups['bastille_jails'] }}"

- name: Ensure Poudriere packages are mounted into jail fstab
  ansible.builtin.lineinfile:
    path: "/usr/local/bastille/jails/{{ item }}/fstab"
    line: "{{ poudriere_host_pkg_dir }} {{ jail_pkg_mount_dir }} nullfs ro 0 0"
    state: present
  loop: "{{ groups['bastille_jails'] }}"

- name: Ensure thick jails are started
  ansible.builtin.command: "bastille start {{ item }}" # noqa: command-instead-of-module
  register: bastille_jail_start
  changed_when: "'Starting' in bastille_jail_start.stdout"
  loop: "{{ groups['bastille_jails'] }}"

- name: Ensure DNS resolution is configured in jails
  ansible.builtin.copy:
    src: /etc/resolv.conf
    dest: "/usr/local/bastille/jails/{{ item }}/root/etc/resolv.conf"
    remote_src: true
    mode: '0644'
  loop: "{{ groups['bastille_jails'] }}"

- name: Ensure Python 3.12 is installed in jails
  ansible.builtin.command: "bastille pkg {{ item }} install -y python312" # noqa: command-instead-of-module
  register: bastille_pkg_python
  changed_when: "'Extracting python312' in bastille_pkg_python.stdout or 'Installing python312' in bastille_pkg_python.stdout"
  loop: "{{ groups['bastille_jails'] }}"
