---
- name: Install Nginx, PHP, and Kanboard
  community.general.pkgng:
    name:
      - nginx
      - php84
      - php84-mysqli
      - php84-pdo_sqlite
      - php84-pdo_pgsql
      - php84-mbstring
      - php84-gd
      - php84-zlib
      - php84-kanboard
      - py312-cryptography
    state: present

- name: Create Nginx conf.d directory
  ansible.builtin.file:
    path: /usr/local/etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Create SSL certificate directory
  ansible.builtin.file:
    path: /usr/local/etc/ssl/kanboard
    state: directory
    mode: '0700'

- name: Generate SSL Private Key
  community.crypto.openssl_privatekey:
    path: /usr/local/etc/ssl/kanboard/kanboard.key
    size: 2048
    type: RSA

- name: Generate OpenSSL Certificate Signing Request (CSR)
  community.crypto.openssl_csr:
    path: /usr/local/etc/ssl/kanboard/kanboard.csr
    privatekey_path: /usr/local/etc/ssl/kanboard/kanboard.key
    common_name: "{{ inventory_hostname }}"

- name: Generate Self-Signed Certificate
  community.crypto.x509_certificate:
    path: /usr/local/etc/ssl/kanboard/kanboard.crt
    privatekey_path: /usr/local/etc/ssl/kanboard/kanboard.key
    csr_path: /usr/local/etc/ssl/kanboard/kanboard.csr
    provider: selfsigned
    selfsigned_not_after: "+365d"

- name: Deploy main php-fpm.conf
  ansible.builtin.template:
    src: php-fpm.conf.j2
    dest: /usr/local/etc/php-fpm.conf
    mode: '0644'
  notify: Restart php-fpm

- name: Deploy php-fpm pool www.conf
  ansible.builtin.template:
    src: www.conf.j2
    dest: /usr/local/etc/php-fpm.d/www.conf
    mode: '0644'
  notify: Restart php-fpm

- name: Deploy php kanboard configuration config.php
  ansible.builtin.template:
    src: kanboard-php.conf.j2
    dest: /usr/local/www/kanboard/config.php
    mode: '0644'
  notify: Restart php-fpm

- name: Deploy main Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf
    mode: '0644'
  notify: Restart nginx

- name: Deploy Kanboard Nginx vhost configuration
  ansible.builtin.template:
    src: kanboard.conf.j2
    dest: /usr/local/etc/nginx/conf.d/kanboard.conf
    mode: '0644'
  notify: Restart nginx

- name: Enable Nginx and PHP-FPM in rc.conf
  community.general.sysrc:
    name: "{{ item }}"
    value: "YES"
  loop:
    - nginx_enable
    - php_fpm_enable

- name: Ensure PHP-FPM and Nginx are running
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  loop:
    - php_fpm
    - nginx
