---
- name: Install Nextcloud, Nginx, and PHP dependencies
  community.general.pkgng:
    name:
      - nginx
      - nextcloud-php83
      - php83-pgsql
      - php83-pdo_pgsql
      - php83-gd
      - php83-curl
      - php83-zip
      - php83-zlib
      - php83-mbstring
      - php83-xml
      - php83-intl
      - php83-bcmath
      - php83-gmp
      - php83-fileinfo
      - php83-opcache
      - php83-pecl-imagick
    state: present

- name: Create Nginx conf.d directory
  ansible.builtin.file:
    path: /usr/local/etc/nginx/conf.d
    state: directory
    mode: '0755'

- name: Create SSL certificate directory
  ansible.builtin.file:
    path: /usr/local/etc/ssl/nextcloud
    state:  directory
    mode: '0700'
  
- name: Generate self-signed SSL certificate if missing
  ansible.builtin.command:
    openssl req -x509 -nodes -days 365 -newkey rsa:2048
    -keyout /usr/local/etc/ssl/nextcloud/nextcloud.key
    -out /usr/local/etc/ssl/nextcloud/nextcloud.crt
    -subj " /CN={{ nextcloud_server_name | default('nextcloud.new') }}"
  args:
    creates: /usr/local/etc/ssl/nextcloud/nextcloud.crt

- name: Deploy main php-fpm.conf
  ansible.builtin.template:
    src: php-fpm.conf.j2
    dest: /usr/local/etc/php-fpm.conf
    mode: '0644'
  notify: Restart php-fpm

- name: Deploy php-fpm pool www.conf
  ansible.builtin.template:
    src: www.conf.j2
    dest: /usr/local/etc/php-fpm.d/www.conf
    mode: '0644'
  notify: Restart php-fpm

- name: Deploy main Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /usr/local/etc/nginx/nginx.conf
    mode: '0644'
  notify: Restart nginx

- name: Deploy Nextcloud Nginx vhost configuration
  ansible.builtin.template:
    src: nextcloud.conf.j2
    dest: /usr/local/etc/nginx/conf.d/nextcloud.conf
    mode: '0644'
  notify: Restart nginx


- name: Enable Nginx and PHP-FPM in rc.conf
  community.general.sysrc:
    name: "{{ item }}"
    value: "YES"
  loop:
    - nginx_enable
    - php_fpm_enable

- name: Ensure PHP-FPM and Nginx are started
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  loop:
    - php-fpm
    - nginx

- name: Run Nextcloud automated installer via occ
  ansible.builtin.command: >
    su -m www -c "php /usr/local/www/nextcloud/occ maintenance:install
    --database='pgsql'
    --database-host='{{ nextcloud_db_host }}'
    --database-name='{{ nextcloud_db_name }}'
    --database-user='{{ nextcloud_db_user }}'
    --database-pass='{{ nextcloud_db_pass }}'
    --admin-user='{{ nextcloud_admin_user }}'
    --admin-pass='{{ nextcloud_admin_pass }}'
  args:
    creates: /usr/local/www/nextcloud/config/config.php
